Repository typescript-cheatsheets/react, pull requests merged in 2020-10, with the labels that each got.

#315 Fixing TOC Code Fence Issue
  genReadme.js
Labels: Hacktoberfest, bug

#318 Added Discriminated Unions with Hooks Example
  CONTRIBUTORS.md
  docs/advanced/patterns_by_usecase.md
  docs/basic/troubleshooting/non-ts-files.md
Labels: ADVANCED, Hacktoberfest

#331 Update links
  docs/advanced/patterns_by_version.md
  docs/basic/linting.md
  docs/basic/setup.md
  docs/basic/troubleshooting/ts-config.md
  docs/migration/index.md
Labels: Hacktoberfest, hacktoberfest-accepted
